server:
  port: 8700
spring:
  redis:
    database: 0 #使用第几个数据库
    host: 192.168.65.135 #redis服务器地址
    port: 6379 #端口号
    password: 123456 #redis服务器连接密码
    timeout: 10000ms  # 连接超时时间（毫秒）
    lettuce:
      pool:
        ##下面的值其实是lettuce连接池的默认配置，有兴趣的可以点进源码看一下
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
